### ISSUE TITLE
The insertion/deletion histogram should be bound to small range with the option to 'show outliers'.

### ISSUE THREAD

**Issue by tonydisera** [tonydisera/vcf.iobio.io#13] opened 2015-11-23 17:48 UTC
In the case where there are large deletions or insertions, the histogram is getting skewed so that the more frequent insertion/deletions are hard to visualize.  The app should figure out the distribution (using standard deviation) so that x-axis is bound to smaller range of bps.

Here's an example, showing how the histogram is skewed based on a very large deletion.

<img width="536" alt="screen shot 2015-11-23 at 10 37 31 am" src="https://cloud.githubusercontent.com/assets/8420103/11344619/b0919724-91cf-11e5-875c-823aec91416b.png">

**Comment by tonydisera** [comment] 2016-06-13 17:46
Fixed with commit [a07aaef]

**Comment by AlistairNWard** [comment] 2016-06-21 12:57
Is there a test file associated with this issue?

**Comment by tonydisera** [comment] 2016-06-21 16:04
This file shows a similar problem with outliers: 
https://s3.amazonaws.com/iobio/app_testing/vcf_files/fails_to_load.vcf.gz

**Comment by AlistairNWard** [comment] 2016-06-21 16:20
I tried running with this file and the outliers button has no effect. The largest event is ~450bp deletion. Are we just rescaling the x axis and not allowing the large variants to be seen? The rescale should occur when the 'Outliers' box is unchecked, but should allow the full range to be seen if checked.

**Comment by tonydisera** [comment] 2016-06-21 16:23
You don't see this?
<img width="522" alt="screenshot 2016-06-21 10 22 20" src="https://cloud.githubusercontent.com/assets/8420103/16237532/279a1e16-379a-11e6-8a80-9756de1153c7.png">

<img width="523" alt="screenshot 2016-06-21 10 22 28" src="https://cloud.githubusercontent.com/assets/8420103/16237535/2c7eb838-379a-11e6-8664-e5d85d5d11c5.png">

**Comment by AlistairNWard** [comment] 2016-06-21 16:29
Hmm. I do now, but I definitely didn't before. Can't reproduce, so I'm going to close it.

**Closed** 2016-06-21 16:30 UTC
