### ISSUE TITLE
Cannot zoom out of variant density

### ISSUE THREAD

**Issue by AlistairNWard** [tonydisera/vcf.iobio.io#5] opened 2015-05-26 21:18 UTC
I zoom in on a region of a chromosome. The variant density is updated to show that region. If I click to deselect the region, the grey zoom window disappears, but nothing is recomputed. I can click on the chromosome wheel, but is the deselect supposed to recompute (analogous to gene.iobio)?

**Comment by tonydisera** [comment] 2016-05-31 17:33
duplicate of #16

**Closed by tonydisera** 2016-05-31 17:33 UTC
Labels: bug
